"""add url entrie to posts table

Revision ID: 0b4d1f34c675
Revises: 6c07e2a8b303
Create Date: 2025-07-12 16:20:56.429094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4d1f34c675'
down_revision = '6c07e2a8b303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
