"""feat:add title_slug column to posts

Revision ID: 1cdcfa24c311
Revises: 0b4d1f34c675
Create Date: 2025-07-29 17:14:12.475639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdcfa24c311'
down_revision = '0b4d1f34c675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_slug', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('title_slug')

    # ### end Alembic commands ###
